"""
Generate a downloadable project scaffold ZIP from a design's AI output.

Reads the design input (preferred_stack, deployment_scope) and output
(core_components, recommended_implementation_phases) to produce an
in-memory ZIP archive containing ready-to-run starter files.
"""

import io
import re
import zipfile
from textwrap import dedent

from app.schemas.design import DesignInputPayload, DesignOutputPayload


# ─── Stack Detection ────────────────────────────────────────────
def _detect(stack: str, keywords: list[str]) -> bool:
    low = stack.lower()
    return any(kw in low for kw in keywords)


# ─── Template Builders ──────────────────────────────────────────
def _readme(title: str, services: list[str]) -> str:
    svc_list = "\n".join(f"- {s}" for s in services)
    return dedent(f"""\
        # {title}

        > Auto-generated scaffold by **SystemForge AI**.

        ## Services

        {svc_list}

        ## Getting Started

        ```bash
        docker compose up --build
        ```

        Then open the application in your browser.
    """)


def _env_example(flags: dict[str, bool]) -> str:
    lines = ["# Auto-generated by SystemForge AI", ""]
    if flags.get("postgres"):
        lines += ["POSTGRES_USER=app", "POSTGRES_PASSWORD=changeme", "POSTGRES_DB=app_db", "DATABASE_URL=postgresql://app:changeme@postgres:5432/app_db", ""]
    if flags.get("mongo"):
        lines += ["MONGO_URL=mongodb://mongo:27017/app_db", ""]
    if flags.get("redis"):
        lines += ["REDIS_URL=redis://redis:6379/0", ""]
    lines += ["NODE_ENV=development", ""]
    return "\n".join(lines)


def _docker_compose(flags: dict[str, bool], title: str) -> str:
    services: dict[str, str] = {}

    if flags.get("fastapi"):
        services["backend"] = dedent("""\
          backend:
            build: ./backend
            ports:
              - "8000:8000"
            env_file: .env
            depends_on:
              - {deps}
            volumes:
              - ./backend:/app
            command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        """)
    elif flags.get("django"):
        services["backend"] = dedent("""\
          backend:
            build: ./backend
            ports:
              - "8000:8000"
            env_file: .env
            depends_on:
              - {deps}
            volumes:
              - ./backend:/app
            command: python manage.py runserver 0.0.0.0:8000
        """)
    elif flags.get("nestjs"):
        services["backend"] = dedent("""\
          backend:
            build: ./backend
            ports:
              - "3001:3001"
            env_file: .env
            depends_on:
              - {deps}
            volumes:
              - ./backend:/app
            command: npm run start:dev
        """)

    if flags.get("nextjs"):
        services["frontend"] = dedent("""\
          frontend:
            build: ./frontend
            ports:
              - "3000:3000"
            env_file: .env
            volumes:
              - ./frontend:/app
            command: npm run dev
        """)
    elif flags.get("vite"):
        services["frontend"] = dedent("""\
          frontend:
            build: ./frontend
            ports:
              - "5173:5173"
            env_file: .env
            volumes:
              - ./frontend:/app
            command: npm run dev -- --host 0.0.0.0
        """)

    if flags.get("postgres"):
        services["postgres"] = dedent("""\
          postgres:
            image: postgres:16-alpine
            environment:
              POSTGRES_USER: app
              POSTGRES_PASSWORD: changeme
              POSTGRES_DB: app_db
            ports:
              - "5432:5432"
            volumes:
              - pgdata:/var/lib/postgresql/data
        """)

    if flags.get("redis"):
        services["redis"] = dedent("""\
          redis:
            image: redis:7-alpine
            ports:
              - "6379:6379"
        """)

    if flags.get("mongo"):
        services["mongo"] = dedent("""\
          mongo:
            image: mongo:7
            ports:
              - "27017:27017"
            volumes:
              - mongodata:/data/db
        """)

    # Build deps list for backend
    deps_list = []
    if flags.get("postgres"):
        deps_list.append("postgres")
    if flags.get("redis"):
        deps_list.append("redis")
    if flags.get("mongo"):
        deps_list.append("mongo")
    deps_str = "\n              - ".join(deps_list) if deps_list else "[]"

    body = ""
    for svc_yaml in services.values():
        body += svc_yaml.replace("{deps}", deps_str)

    volumes_section = ""
    vol_names: list[str] = []
    if flags.get("postgres"):
        vol_names.append("pgdata:")
    if flags.get("mongo"):
        vol_names.append("mongodata:")
    if vol_names:
        volumes_section = "\nvolumes:\n" + "\n".join(f"  {v}" for v in vol_names) + "\n"

    return dedent(f"""\
        # {title} — Docker Compose
        # Auto-generated by SystemForge AI

        services:
        {body}{volumes_section}""")


# ─── Framework Stubs ────────────────────────────────────────────
def _fastapi_files(zf: zipfile.ZipFile) -> None:
    zf.writestr("backend/Dockerfile", dedent("""\
        FROM python:3.12-slim
        WORKDIR /app
        COPY requirements.txt .
        RUN pip install --no-cache-dir -r requirements.txt
        COPY . .
        CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    """))
    zf.writestr("backend/requirements.txt", dedent("""\
        fastapi>=0.115
        uvicorn[standard]>=0.30
        sqlalchemy>=2.0
        alembic>=1.13
        psycopg2-binary>=2.9
        pydantic>=2.7
        python-dotenv>=1.0
    """))
    zf.writestr("backend/app/__init__.py", "")
    zf.writestr("backend/app/main.py", dedent("""\
        from fastapi import FastAPI
        from fastapi.middleware.cors import CORSMiddleware

        app = FastAPI(title="API", version="0.1.0")

        app.add_middleware(
            CORSMiddleware,
            allow_origins=["*"],
            allow_credentials=True,
            allow_methods=["*"],
            allow_headers=["*"],
        )


        @app.get("/health")
        def health():
            return {"status": "ok"}
    """))


def _django_files(zf: zipfile.ZipFile) -> None:
    zf.writestr("backend/Dockerfile", dedent("""\
        FROM python:3.12-slim
        WORKDIR /app
        COPY requirements.txt .
        RUN pip install --no-cache-dir -r requirements.txt
        COPY . .
        CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    """))
    zf.writestr("backend/requirements.txt", dedent("""\
        django>=5.0
        djangorestframework>=3.15
        psycopg2-binary>=2.9
        python-dotenv>=1.0
    """))
    zf.writestr("backend/manage.py", dedent("""\
        #!/usr/bin/env python
        import os, sys

        if __name__ == "__main__":
            os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
            from django.core.management import execute_from_command_line
            execute_from_command_line(sys.argv)
    """))
    zf.writestr("backend/config/__init__.py", "")
    zf.writestr("backend/config/settings.py", "# Django settings — configure your database, installed apps, etc.\n")


def _nestjs_files(zf: zipfile.ZipFile) -> None:
    zf.writestr("backend/Dockerfile", dedent("""\
        FROM node:22-alpine
        WORKDIR /app
        COPY package.json .
        RUN npm install
        COPY . .
        CMD ["npm", "run", "start:dev"]
    """))
    zf.writestr("backend/package.json", dedent("""\
        {
          "name": "backend",
          "version": "0.1.0",
          "scripts": {
            "start:dev": "nest start --watch",
            "build": "nest build",
            "start": "node dist/main"
          },
          "dependencies": {
            "@nestjs/common": "^10",
            "@nestjs/core": "^10",
            "@nestjs/platform-express": "^10",
            "reflect-metadata": "^0.2",
            "rxjs": "^7"
          },
          "devDependencies": {
            "@nestjs/cli": "^10",
            "typescript": "^5"
          }
        }
    """))
    zf.writestr("backend/src/main.ts", dedent("""\
        import { NestFactory } from '@nestjs/core';
        import { AppModule } from './app.module';

        async function bootstrap() {
          const app = await NestFactory.create(AppModule);
          app.enableCors();
          await app.listen(3001);
        }
        bootstrap();
    """))
    zf.writestr("backend/src/app.module.ts", dedent("""\
        import { Module } from '@nestjs/common';
        @Module({ imports: [], controllers: [], providers: [] })
        export class AppModule {}
    """))


def _nextjs_files(zf: zipfile.ZipFile) -> None:
    zf.writestr("frontend/Dockerfile", dedent("""\
        FROM node:22-alpine
        WORKDIR /app
        COPY package.json .
        RUN npm install
        COPY . .
        CMD ["npm", "run", "dev"]
    """))
    zf.writestr("frontend/package.json", dedent("""\
        {
          "name": "frontend",
          "version": "0.1.0",
          "scripts": {
            "dev": "next dev",
            "build": "next build",
            "start": "next start"
          },
          "dependencies": {
            "next": "^15",
            "react": "^19",
            "react-dom": "^19"
          },
          "devDependencies": {
            "typescript": "^5",
            "@types/react": "^19",
            "@types/node": "^22"
          }
        }
    """))
    zf.writestr("frontend/app/page.tsx", dedent("""\
        export default function Home() {
          return (
            <main style={{ padding: "2rem", fontFamily: "system-ui" }}>
              <h1>Welcome</h1>
              <p>Your Next.js frontend is running.</p>
            </main>
          );
        }
    """))
    zf.writestr("frontend/app/layout.tsx", dedent("""\
        export const metadata = { title: "App" };
        export default function RootLayout({ children }: { children: React.ReactNode }) {
          return <html lang="en"><body>{children}</body></html>;
        }
    """))


def _vite_files(zf: zipfile.ZipFile) -> None:
    zf.writestr("frontend/Dockerfile", dedent("""\
        FROM node:22-alpine
        WORKDIR /app
        COPY package.json .
        RUN npm install
        COPY . .
        CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    """))
    zf.writestr("frontend/package.json", dedent("""\
        {
          "name": "frontend",
          "version": "0.1.0",
          "scripts": { "dev": "vite", "build": "vite build", "preview": "vite preview" },
          "dependencies": { "react": "^19", "react-dom": "^19" },
          "devDependencies": { "vite": "^6", "@vitejs/plugin-react": "^4", "typescript": "^5" }
        }
    """))
    zf.writestr("frontend/index.html", dedent("""\
        <!DOCTYPE html>
        <html lang="en">
        <head><meta charset="UTF-8" /><title>App</title></head>
        <body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body>
        </html>
    """))
    zf.writestr("frontend/src/main.tsx", dedent("""\
        import React from "react";
        import ReactDOM from "react-dom/client";

        ReactDOM.createRoot(document.getElementById("root")!).render(
          <React.StrictMode><h1>Vite + React</h1></React.StrictMode>
        );
    """))


# ─── Main Entry ─────────────────────────────────────────────────
def build_scaffold_zip(
    title: str,
    design_input: DesignInputPayload,
    design_output: DesignOutputPayload,
) -> bytes:
    """Return in-memory ZIP bytes for the project scaffold."""

    stack = (design_input.preferred_stack or "") + " " + " ".join(design_output.core_components)

    flags: dict[str, bool] = {
        "fastapi": _detect(stack, ["fastapi", "fast api"]),
        "django": _detect(stack, ["django"]),
        "nestjs": _detect(stack, ["nestjs", "nest.js", "nest js"]),
        "nextjs": _detect(stack, ["nextjs", "next.js", "next js"]),
        "vite": _detect(stack, ["vite", "react"]) and not _detect(stack, ["nextjs", "next.js", "next js"]),
        "postgres": _detect(stack, ["postgres", "postgresql", "pg"]),
        "redis": _detect(stack, ["redis"]),
        "mongo": _detect(stack, ["mongo", "mongodb"]),
    }

    # Ensure at least one backend + frontend
    if not any(flags.get(k) for k in ["fastapi", "django", "nestjs"]):
        flags["fastapi"] = True  # default backend
    if not any(flags.get(k) for k in ["nextjs", "vite"]):
        flags["nextjs"] = True  # default frontend
    if not any(flags.get(k) for k in ["postgres", "mongo"]):
        flags["postgres"] = True  # default database

    service_names = [k for k, v in flags.items() if v]

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")[:48] or "project"  # type: ignore

        zf.writestr(f"{slug}/README.md", _readme(title, service_names))
        zf.writestr(f"{slug}/.env.example", _env_example(flags))
        zf.writestr(f"{slug}/docker-compose.yml", _docker_compose(flags, title))
        zf.writestr(f"{slug}/.gitignore", "node_modules/\n__pycache__/\n.env\n*.pyc\n.next/\ndist/\n")

        # Write framework files with slug prefix
        inner_buf = io.BytesIO()
        with zipfile.ZipFile(inner_buf, "w", zipfile.ZIP_DEFLATED) as inner_zf:
            if flags.get("fastapi"):
                _fastapi_files(inner_zf)
            elif flags.get("django"):
                _django_files(inner_zf)
            elif flags.get("nestjs"):
                _nestjs_files(inner_zf)

            if flags.get("nextjs"):
                _nextjs_files(inner_zf)
            elif flags.get("vite"):
                _vite_files(inner_zf)

        inner_buf.seek(0)
        with zipfile.ZipFile(inner_buf, "r") as inner_zf:
            for item in inner_zf.infolist():
                zf.writestr(f"{slug}/{item.filename}", inner_zf.read(item.filename))

    return buf.getvalue()
