"""Add workspace

Revision ID: f76e4a9f0333
Revises: 0008_share_token
Create Date: 2026-04-13 12:35:44.046629
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f76e4a9f0333'
down_revision = '0008_share_token'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'editor', 'viewer', name='role_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_member')
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.add_column('designs', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.alter_column('designs', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_designs_workspace_id'), 'designs', ['workspace_id'], unique=False)
    op.drop_constraint('designs_owner_id_fkey', 'designs', type_='foreignkey')
    op.create_foreign_key(None, 'designs', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'designs', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('default_workspace_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'workspaces', ['default_workspace_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'default_workspace_id')
    op.drop_constraint(None, 'designs', type_='foreignkey')
    op.drop_constraint(None, 'designs', type_='foreignkey')
    op.create_foreign_key('designs_owner_id_fkey', 'designs', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_designs_workspace_id'), table_name='designs')
    op.alter_column('designs', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('designs', 'workspace_id')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
